/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Cadastros;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import utilitarios.Conexao;

/**
 *
 * @author Danilo 
 */
public class Cad_clientes extends javax.swing.JFrame {

    /**
     * Creates new form Cad_clientes
     */
    Conexao con_clientes;
    int navega = 0;
    public Cad_clientes() {
        initComponents();
       
          /*mudar cor da tela*/
        this.getContentPane().setBackground(Color.WHITE);
        
        /*mudar icone*/
       URL url = this.getClass().getResource("/Utilitarios/Database.png");  
Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);  
this.setIconImage(imagemTitulo);

/*chamando o metodo conecta*/
con_clientes = new Conexao();
        con_clientes.conecta();
        con_clientes.executeSQL("select * from cliente");
       try
        {
           
           con_clientes.resultset.first();
           navega =1;
           mostrar_dados();
        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null,"Não Localizou o erro: "+erro);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_nome = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_ende = new javax.swing.JTextField();
        cb_sexo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jb_salvar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        tf_dn = new javax.swing.JFormattedTextField();
        jb_anterior = new javax.swing.JButton();
        jb_proximo = new javax.swing.JButton();
        jb_novo = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jl_codigo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 23));
        getContentPane().add(tf_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 450, 23));

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastro de Clientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(315, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, -1));

        jLabel3.setText("Data de Nascimento:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, -1, -1));

        jLabel4.setText("Endereço:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
        getContentPane().add(tf_ende, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 150, 670, -1));

        cb_sexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Masculino", "Feminino" }));
        getContentPane().add(cb_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 90, -1));

        jLabel5.setText("Sexo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jb_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitarios/Save.png"))); // NOI18N
        jb_salvar.setText("Salvar");
        jb_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salvarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 100, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitarios/Close.png"))); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 100, -1));

        tf_dn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        getContentPane().add(tf_dn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 91, -1));

        jb_anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitarios/Go back.png"))); // NOI18N
        jb_anterior.setText("Anterior");
        jb_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_anteriorActionPerformed(evt);
            }
        });
        getContentPane().add(jb_anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 262, 100, -1));

        jb_proximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitarios/Go forward.png"))); // NOI18N
        jb_proximo.setText("Proximo");
        jb_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_proximoActionPerformed(evt);
            }
        });
        getContentPane().add(jb_proximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 100, -1));

        jb_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitarios/New document.png"))); // NOI18N
        jb_novo.setText("Novo");
        jb_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_novoActionPerformed(evt);
            }
        });
        getContentPane().add(jb_novo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 100, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilitarios/deletes.gif"))); // NOI18N
        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 100, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jl_codigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_codigo.setForeground(new java.awt.Color(0, 0, 153));

        jLabel6.setText("Código:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jl_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jl_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 130, 60));

        setSize(new java.awt.Dimension(805, 444));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jb_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_proximoActionPerformed
    try
        {
            con_clientes.resultset.next();
            mostrar_dados();
            navega = 2;
        }
        catch(SQLException erro)
        {
 JOptionPane.showMessageDialog(null,"Não foi possível ir para o próximo registro "+erro);
        }       // TODO add your handling code here:
    }//GEN-LAST:event_jb_proximoActionPerformed

    private void jb_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_anteriorActionPerformed
       try
        {
            con_clientes.resultset.previous();
            mostrar_dados();
            navega = 2;
        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null,"Não foi possível ir para o próximo registro "+erro);
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jb_anteriorActionPerformed

    private void jb_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_novoActionPerformed
        Conexao limpar = new Conexao();
        limpar.conecta();
        jl_codigo.setText("");
        tf_nome.setText("");
        tf_dn.setText("");
        tf_ende.setText("");
        cb_sexo.setSelectedItem("-");
        tf_nome.requestFocus();
// TODO add your handling code here:
    }//GEN-LAST:event_jb_novoActionPerformed

    private void jb_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salvarActionPerformed
try
{
String sqlinsert ="insert into cliente (nome,dn,endereco,sexo) values ('"+
tf_nome.getText()+"','"+
tf_dn.getText()+"','"+
tf_ende.getText()+"','"+
cb_sexo.getSelectedItem()+"')";
con_clientes.statement.executeUpdate(sqlinsert);
JOptionPane.showMessageDialog(null,"Gravação realizado com sucesso!");

con_clientes.executeSQL("select * from cliente");
con_clientes.resultset.first(); //posiciona no primeiro registro
mostrar_dados(); //irá chamar a função em que irá mstrar os dados no form
}
catch (SQLException erro)
{
JOptionPane.showMessageDialog(null,"Erro a tentar Gravar o registro..."+erro);
}         // TODO add your handling code here:
    }//GEN-LAST:event_jb_salvarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cad_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cad_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cad_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cad_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cad_clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb_sexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jb_anterior;
    private javax.swing.JButton jb_novo;
    private javax.swing.JButton jb_proximo;
    private javax.swing.JButton jb_salvar;
    private javax.swing.JLabel jl_codigo;
    private javax.swing.JFormattedTextField tf_dn;
    private javax.swing.JTextField tf_ende;
    private javax.swing.JTextField tf_nome;
    // End of variables declaration//GEN-END:variables

    
    
    public void mostrar_dados()
    {
        try
        {  
             jl_codigo.setText(con_clientes.resultset.getString("codigo"));
            tf_nome.setText(con_clientes.resultset.getString("nome"));
             tf_dn.setText(con_clientes.resultset.getString("dn"));
            tf_ende.setText(con_clientes.resultset.getString("endereco"));
            cb_sexo.setSelectedItem(con_clientes.resultset.getString("sexo"));
        }
        catch(SQLException erro)
        {
           
if (navega == 1)
JOptionPane.showMessageDialog(null,"Você já está no primeiro registro");
else if (navega == 2)
JOptionPane.showMessageDialog(null,"Você já está no último registro");
else
JOptionPane.showMessageDialog(null,"Não localizou dados "+erro);
navega=0;
}
        }
}
